language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - bin/phpunit --verbose

after_failure:
  - cat server.log
  - sudo cat /var/log/nginx/error.log
  - sudo cat /var/log/nginx/access.log

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.4
    - php: 7.0
  fast_finish: true
